# Generated by Django 2.2.6 on 2019-10-27 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('type', models.PositiveIntegerField(choices=[(0, 'Обычная задача'), (1, 'Срочная задача'), (2, 'Важная задача!'), (3, 'Другое')], default=0, verbose_name='Тип задачи')),
                ('task', models.CharField(max_length=200, verbose_name='Тема')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('file', models.FileField(blank=True, upload_to='task_files')),
                ('status', models.NullBooleanField(verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_files', verbose_name='Файл')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.Task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('about', models.TextField(verbose_name='Про достижение')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Начала времени')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Конец времени')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.Task', verbose_name='Задача')),
            ],
        ),
    ]
