# Generated by Django 2.2.6 on 2019-10-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantage',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижение'},
        ),
    ]
