# Generated by Django 2.2.6 on 2019-10-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0002_auto_20191027_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
    ]
