# Generated by Django 2.2.6 on 2019-10-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0003_remove_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Не Активно'), (1, 'Активно'), (2, 'В прогрессе'), (3, 'Завершено'), (4, 'Просрочено')], default=1, verbose_name='Статус'),
        ),
    ]
