# Generated by Django 2.2.6 on 2019-10-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0004_auto_20191027_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, upload_to='task_files'),
        ),
    ]
