# Generated by Django 2.2.6 on 2019-11-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0005_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='username',
            field=models.CharField(default='user', max_length=255, verbose_name='Имя'),
        ),
    ]
