# Generated by Django 2.2.6 on 2019-11-12 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ais', '0006_advantage_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('feedback', models.TextField(verbose_name='Отзыв')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('advantage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.Advantage', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
