# Generated by Django 2.2.6 on 2019-11-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='see',
            field=models.IntegerField(default=1, verbose_name='Просмотров'),
        ),
    ]
