# Generated by Django 2.2.6 on 2019-10-17 15:36

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', django_mysql.models.EnumField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='1')),
                ('status', django_mysql.models.EnumField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='1')),
                ('desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField()),
                ('perfomer_id', models.IntegerField()),
                ('card_id', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('creator_id', models.IntegerField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PanelUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('panel_id', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
